/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PTokenRouteImport } from './routes/p/$token'
import { Route as AuthedPrintRouteImport } from './routes/_authed/print'
import { Route as AuthedOnboardingRouteImport } from './routes/_authed/onboarding'
import { Route as AuthedAppRouteImport } from './routes/_authed/_app'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedAppTimetableRouteImport } from './routes/_authed/_app/timetable'
import { Route as AuthedAppTermsRouteImport } from './routes/_authed/_app/terms'
import { Route as AuthedAppTeachersRouteImport } from './routes/_authed/_app/teachers'
import { Route as AuthedAppSubjectsRouteImport } from './routes/_authed/_app/subjects'
import { Route as AuthedAppShareRouteImport } from './routes/_authed/_app/share'
import { Route as AuthedAppScheduleRouteImport } from './routes/_authed/_app/schedule'
import { Route as AuthedAppGradesRouteImport } from './routes/_authed/_app/grades'
import { Route as AuthedAppDashboardRouteImport } from './routes/_authed/_app/dashboard'
import { Route as AuthedAppCurriculumRouteImport } from './routes/_authed/_app/curriculum'
import { Route as AuthedAppClassesRouteImport } from './routes/_authed/_app/classes'
import { Route as AuthedAppAssignmentsRouteImport } from './routes/_authed/_app/assignments'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedPrintRoute = AuthedPrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOnboardingRoute = AuthedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAppRoute = AuthedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAppTimetableRoute = AuthedAppTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppTermsRoute = AuthedAppTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppTeachersRoute = AuthedAppTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppSubjectsRoute = AuthedAppSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppShareRoute = AuthedAppShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppScheduleRoute = AuthedAppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppGradesRoute = AuthedAppGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppDashboardRoute = AuthedAppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppCurriculumRoute = AuthedAppCurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppClassesRoute = AuthedAppClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppAssignmentsRoute = AuthedAppAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AuthedAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/print': typeof AuthedPrintRoute
  '/p/$token': typeof PTokenRoute
  '/assignments': typeof AuthedAppAssignmentsRoute
  '/classes': typeof AuthedAppClassesRoute
  '/curriculum': typeof AuthedAppCurriculumRoute
  '/dashboard': typeof AuthedAppDashboardRoute
  '/grades': typeof AuthedAppGradesRoute
  '/schedule': typeof AuthedAppScheduleRoute
  '/share': typeof AuthedAppShareRoute
  '/subjects': typeof AuthedAppSubjectsRoute
  '/teachers': typeof AuthedAppTeachersRoute
  '/terms': typeof AuthedAppTermsRoute
  '/timetable': typeof AuthedAppTimetableRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/print': typeof AuthedPrintRoute
  '/p/$token': typeof PTokenRoute
  '/assignments': typeof AuthedAppAssignmentsRoute
  '/classes': typeof AuthedAppClassesRoute
  '/curriculum': typeof AuthedAppCurriculumRoute
  '/dashboard': typeof AuthedAppDashboardRoute
  '/grades': typeof AuthedAppGradesRoute
  '/schedule': typeof AuthedAppScheduleRoute
  '/share': typeof AuthedAppShareRoute
  '/subjects': typeof AuthedAppSubjectsRoute
  '/teachers': typeof AuthedAppTeachersRoute
  '/terms': typeof AuthedAppTermsRoute
  '/timetable': typeof AuthedAppTimetableRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authed/_app': typeof AuthedAppRouteWithChildren
  '/_authed/onboarding': typeof AuthedOnboardingRoute
  '/_authed/print': typeof AuthedPrintRoute
  '/p/$token': typeof PTokenRoute
  '/_authed/_app/assignments': typeof AuthedAppAssignmentsRoute
  '/_authed/_app/classes': typeof AuthedAppClassesRoute
  '/_authed/_app/curriculum': typeof AuthedAppCurriculumRoute
  '/_authed/_app/dashboard': typeof AuthedAppDashboardRoute
  '/_authed/_app/grades': typeof AuthedAppGradesRoute
  '/_authed/_app/schedule': typeof AuthedAppScheduleRoute
  '/_authed/_app/share': typeof AuthedAppShareRoute
  '/_authed/_app/subjects': typeof AuthedAppSubjectsRoute
  '/_authed/_app/teachers': typeof AuthedAppTeachersRoute
  '/_authed/_app/terms': typeof AuthedAppTermsRoute
  '/_authed/_app/timetable': typeof AuthedAppTimetableRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/onboarding'
    | '/print'
    | '/p/$token'
    | '/assignments'
    | '/classes'
    | '/curriculum'
    | '/dashboard'
    | '/grades'
    | '/schedule'
    | '/share'
    | '/subjects'
    | '/teachers'
    | '/terms'
    | '/timetable'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/onboarding'
    | '/print'
    | '/p/$token'
    | '/assignments'
    | '/classes'
    | '/curriculum'
    | '/dashboard'
    | '/grades'
    | '/schedule'
    | '/share'
    | '/subjects'
    | '/teachers'
    | '/terms'
    | '/timetable'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/signup'
    | '/_authed/_app'
    | '/_authed/onboarding'
    | '/_authed/print'
    | '/p/$token'
    | '/_authed/_app/assignments'
    | '/_authed/_app/classes'
    | '/_authed/_app/curriculum'
    | '/_authed/_app/dashboard'
    | '/_authed/_app/grades'
    | '/_authed/_app/schedule'
    | '/_authed/_app/share'
    | '/_authed/_app/subjects'
    | '/_authed/_app/teachers'
    | '/_authed/_app/terms'
    | '/_authed/_app/timetable'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  PTokenRoute: typeof PTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/print': {
      id: '/_authed/print'
      path: '/print'
      fullPath: '/print'
      preLoaderRoute: typeof AuthedPrintRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/onboarding': {
      id: '/_authed/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthedOnboardingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_app': {
      id: '/_authed/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedAppRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_app/timetable': {
      id: '/_authed/_app/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof AuthedAppTimetableRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/terms': {
      id: '/_authed/_app/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof AuthedAppTermsRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/teachers': {
      id: '/_authed/_app/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof AuthedAppTeachersRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/subjects': {
      id: '/_authed/_app/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof AuthedAppSubjectsRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/share': {
      id: '/_authed/_app/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof AuthedAppShareRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/schedule': {
      id: '/_authed/_app/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthedAppScheduleRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/grades': {
      id: '/_authed/_app/grades'
      path: '/grades'
      fullPath: '/grades'
      preLoaderRoute: typeof AuthedAppGradesRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/dashboard': {
      id: '/_authed/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedAppDashboardRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/curriculum': {
      id: '/_authed/_app/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof AuthedAppCurriculumRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/classes': {
      id: '/_authed/_app/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthedAppClassesRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/assignments': {
      id: '/_authed/_app/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AuthedAppAssignmentsRouteImport
      parentRoute: typeof AuthedAppRoute
    }
  }
}

interface AuthedAppRouteChildren {
  AuthedAppAssignmentsRoute: typeof AuthedAppAssignmentsRoute
  AuthedAppClassesRoute: typeof AuthedAppClassesRoute
  AuthedAppCurriculumRoute: typeof AuthedAppCurriculumRoute
  AuthedAppDashboardRoute: typeof AuthedAppDashboardRoute
  AuthedAppGradesRoute: typeof AuthedAppGradesRoute
  AuthedAppScheduleRoute: typeof AuthedAppScheduleRoute
  AuthedAppShareRoute: typeof AuthedAppShareRoute
  AuthedAppSubjectsRoute: typeof AuthedAppSubjectsRoute
  AuthedAppTeachersRoute: typeof AuthedAppTeachersRoute
  AuthedAppTermsRoute: typeof AuthedAppTermsRoute
  AuthedAppTimetableRoute: typeof AuthedAppTimetableRoute
}

const AuthedAppRouteChildren: AuthedAppRouteChildren = {
  AuthedAppAssignmentsRoute: AuthedAppAssignmentsRoute,
  AuthedAppClassesRoute: AuthedAppClassesRoute,
  AuthedAppCurriculumRoute: AuthedAppCurriculumRoute,
  AuthedAppDashboardRoute: AuthedAppDashboardRoute,
  AuthedAppGradesRoute: AuthedAppGradesRoute,
  AuthedAppScheduleRoute: AuthedAppScheduleRoute,
  AuthedAppShareRoute: AuthedAppShareRoute,
  AuthedAppSubjectsRoute: AuthedAppSubjectsRoute,
  AuthedAppTeachersRoute: AuthedAppTeachersRoute,
  AuthedAppTermsRoute: AuthedAppTermsRoute,
  AuthedAppTimetableRoute: AuthedAppTimetableRoute,
}

const AuthedAppRouteWithChildren = AuthedAppRoute._addFileChildren(
  AuthedAppRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAppRoute: typeof AuthedAppRouteWithChildren
  AuthedOnboardingRoute: typeof AuthedOnboardingRoute
  AuthedPrintRoute: typeof AuthedPrintRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAppRoute: AuthedAppRouteWithChildren,
  AuthedOnboardingRoute: AuthedOnboardingRoute,
  AuthedPrintRoute: AuthedPrintRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  PTokenRoute: PTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
